# .goreleaser.yml
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: env-lease
    main: ./cmd/env-lease
    binary: env-lease
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: env-leased
    main: ./cmd/env-leased
    binary: env-leased
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
checksum:
  name_template: 'checksums.txt'

homebrew_casks:
  - name: env-lease
    repository:
      owner: mblarsen
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/mblarsen/env-lease"
    description: "A CLI for managing temporary, leased secrets in environment files."
    service: |
      run [opt_bin/"env-leased", "daemon", "run"]
      keep_alive true
