default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 645165368711be670d1945c15060e746f5ed15c6
    hooks:
      - id: go-imports
        args: ["-w"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.29
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data with TruffleHog.
        entry: trufflehog git file://. --since-commit HEAD --results=verified --fail
        language: golang
        pass_filenames: false
        stages:
          - pre-push

  - repo: local
    hooks:
    -   id: go-build-linux
        name: Go Build (linux/amd64)
        language: golang
        types: [go]
        pass_filenames: false
        stages:
          - pre-push
        entry: bash -c 'GOOS=linux GOARCH=amd64 go build ./...'
